apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-virtualservice
  namespace: personal
spec:
  hosts:
  - "scott.murray.kiwi"
  - "scott-the-programmer.com"
  gateways:
  - meshed-gateway.istio-ingress
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: blog
        port:
          number: 9080
