apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: satellites-ingress
  namespace: personal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - "api.murray.kiwi"
    secretName: ingress-api-cert
  rules:
  - host: "api.murray.kiwi"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: satellite-api
            port:
              number: 80
