apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: term-nz-ingress
  namespace: personal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - "term.nz"
    secretName: ingress-term-cert
  rules:
  - host: "term.nz"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: term-nz
            port:
              number: 80
