apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: term-nz-virtualservice
  namespace: personal
spec:
  hosts:
  - "term.nz"
  gateways:
  - istio-ingress/meshed-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: term-nz
        port:
          number: 80
